# data.R
#
# Contains documentation for datasets used in this project.

#' Liver malfunction dataset
#'
#' Observations on 345 men in detailed report on liver malfunctions.
#'
#' @format A data frame with seven variables:
#' \describe{
#'    \item{\code{blood.1}}{Quantitative results from undisclosed blood test related
#'  to liver function.}
#'    \item{\code{blood.2}}{Quantitative results from undisclosed blood test related
#'  to liver function.}
#'    \item{\code{blood.3}}{Quantitative results from undisclosed blood test related
#'  to liver function.}
#'    \item{\code{blood.4}}{Quantitative results from undisclosed blood test related
#'  to liver function.}
#'    \item{\code{blood.5}}{Quantitative results from undisclosed blood test related
#'  to liver function.}
#'    \item{\code{drinks}}{Number of alcoholic beverages reported as consumed.}
#'    \item{\code{severity}}{Severity of liver malfunction. Group 1 indicates severe
#'  malfunction.}
#' }
#'
#' @source Data provided by course instructor.
#'
"liver_data"

#' Severity group mapping
#'
#' Lookup table containing original severity groups mapped to the
#' positive and negative class labels.
#'
#' @format A data frame:
#' \describe{
#'    \item{\code{status}}{Human-readable name for the severity group.}
#'    \item{\code{value}}{Group number used in original dataset.}
#'    \item{\code{code}}{Mapped class label for severity status..}
#' }
#'
#' @source Table generated by `data-raw/severity_map.R`
#'
"severity_map"
